### ISSUE TITLE
CVE URL returning invalid

### ISSUE THREAD

**Issue by bagnaram** [openshift/image-inspector#101]
When automatically retrieving the https://www.redhat.com/security/data/metrics/ds/com.redhat.rhsa-RHEL7.ds.xml.bz2 file to /tmp/ the contents are invalid and contain: Perhaps there are invalid headers being inserted in the HTTP get but I do not have a way to debug this because there are no verbose loggings.
```
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
You don't have permission to access "http&#58;&#47;&#47;www&#46;redhat&#46;com&#47;security&#47;data&#47;metrics&#47;ds&#47;com&#46;redhat&#46;rhsa&#45;RHEL7&#46;ds&#46;xm1&#46;b22" on this server.<P>
Reference&#32;&#35;18&#46;5e962317&#46;1 36093256&#46;1295892e
</BODY>
</HTML>
```

**Comment by simon3z** [comment]
@cben @nimrodshn is this something you recently fixed?

**Comment by cben** [comment]
I think @nimrodshn has mentioned 403 on one of the bugzillas related to #100, specifically in https://bugzilla.redhat.com/show_bug.cgi?id=1620068#c17 (private comment).
I'm not sure if that's the same or a separate problem.  cc @yaacov who might also know.

@bagnaram could you try `openshift/image-inspector@sha256:9f9958ab51cb1aeb02d4609aa63d355238a7e5137cd4da90215378e4bcdae053` which should include #100 (that's current `latest`, [build details](https://hub.docker.com/r/openshift/image-inspector/builds/bgv2ly5mfeenc5jk2yvefwk/)) and tell us if it helps?

**Comment by bagnaram** [comment]
I see. I will re-do my test because I am running using the RPM based image-inspector within a Jenkins slave

**Comment by bagnaram** [comment]
@cben Thank you that worked. I suppose the RPM version was way behind and that was the issue.

**Comment by bagnaram** [comment]
Any idea when this update will make it to registry.access.redhat.com?
