### ISSUE TITLE
Unable to Parse result XML, Using HTML report instead of ARF

### ISSUE THREAD

**Issue by bagnaram** [openshift/image-inspector#105]
Recent reports from image-inspector oscap provide a minified HTML document with css-minify and jquery bundled. This causes syntax parsing issues when `go-xmldom` is used and fails the parsing stage.

**Comment by bagnaram** [comment]
`Error parsing result XML: XML syntax error on line 17: invalid character entity & (no semicolon)`

**Comment by bagnaram** [comment]
Actually this error is being caused because the `results.html` is invalidly being parsed with ParseResults instead of `results-arf.xml`

**Comment by bagnaram** [comment]
Bug found: if `--openscap-html-report` is specified, the parsing defaults to the HTML file instead of the ARF. The parsing should be done on the ARF whether or not an HTML is generated.

**Comment by bagnaram** [comment]
PR submitted
https://github.com/openshift/image-inspector/pull/106

**Comment by bparees** [comment]
@bagnaram @nimrodshn can this be closed based on https://github.com/openshift/image-inspector/pull/106 merging?
