### ISSUE TITLE
Impossible to list etc directory: multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by simon3z** [openshift/image-inspector#11]
Running:

```
# cadaver http://127.0.0.1:8080/api/v1/content/
```

And listing `etc` I get:

```
dav:/api/v1/content/> ls etc
Listing collection `/api/v1/content/etc/': failed:
XML parse error at line 1: junk after document element
```

and on the server side:

```
2016/05/16 08:23:53 http: multiple response.WriteHeader calls
```

cc @enoodle

**Comment by enoodle** [comment]
My guess is that there are two bugs here. One in webdav that tries to write about the first one it encounters while listing ```/etc/``` but it causes the ```multiple response.WriteHeader calls``` so we can't see the first one's error message. I tried updating webdav but it didn't help so far.

**Comment by enoodle** [comment]
I put puts debugging in webdav, my initial guess turned out to be right. The first error is due to ```/etc/rhsm-host``` being a broken link:
```
0 lrwxrwxrwx. 1 root root 17 May 26 16:34 rhsm-host -> /run/secrets/rhsm
```

@simon3z  Do you happen know what is this file and where does it come from?
Other than that there is a bug in golang's webdav..

**Comment by simon3z** [comment]
@enoodle webdav should be able to deal with broken links (somehow) not just error our.

**Comment by enoodle** [comment]
After some more debugging I think that this is a problem in the webdav library. I opened an issue:
[1] https://github.com/golang/go/issues/16195
