### ISSUE TITLE
Force to pull the latest image from registry

### ISSUE THREAD

**Issue by simon3z** [openshift/image-inspector#14]
I haven't double checked the current behavior but I have the feeling that at the moment `image-inspector` is not trying to pull the latest image from the registry.

We should add an option (and discuss what's the default beahvir) to try and pull the latest image from the registry.

cc @enoodle @pweil-

**Comment by enoodle** [comment]
@simon3z It is indeed not trying to pull new versions of the image. A quick fix can be to remove the test  for existing image. It will be always try to pull but we won't have a different message for the case that the image did'nt need refreshing.

**Comment by simon3z** [comment]
> It will be always try to pull but we won't have a different message for the case that the image did'nt need refreshing.

@enoodle why not? you can check the id before and after the pull tentative.

**Comment by enoodle** [comment]
@simon3z Yes. I am also checking another option that goes together with solving #13 but for now I will make a fix just for this.
