### ISSUE TITLE
OpenSCAP Error: Could not read from bZ2FILE: DATA_ERROR_MAGIC

### ISSUE THREAD

**Issue by simon3z** [openshift/image-inspector#19]
When running `image-inspector` I sometimes get:

```
2016/06/16 11:28:46 Unable to scan image: Unable to run OpenSCAP: OpenSCAP error: 1: exit status 1
Input:
[xccdf eval --results-arf /var/tmp/image-inspector-scan-results-727398075/results-arf.xml /tmp/com.redhat.rhsa-RHEL6.ds.xml.bz2]
Output:
url:1: parser error : Document is empty
OpenSCAP Error: Could not read from bZ2FILE: DATA_ERROR_MAGIC [bz2.c:83]
```

In the log I am missing what url was used to download `com.redhat.rhsa-RHEL6.ds.xml.bz2` and other useful information.

cc @enoodle

**Comment by enoodle** [comment]
I can't reproduce this so far, do you want to add some deeper log level in the meantime to print things like this download url?
