### ISSUE TITLE
File extraction fails on docker 1.12.3-9.git47e22f2

### ISSUE THREAD

**Issue by simon3z** [openshift/image-inspector#31]
I don't know exactly what versions of docker are affected but with docker-1.12.3-9.git47e22f2.fc25.x86_64 the extraction is not working, in fact image-inspector blocks on:

```
$ ./image-inspector --image=docker.io/nginx:latest --serve=0.0.0.0:8080
2016/11/29 13:13:59 Pulling image docker.io/nginx:latest
2016/11/29 13:14:02 Finished Downloading Image (0Kb downloaded)
2016/11/29 13:14:02 Extracting image docker.io/nginx:latest to /var/tmp/image-inspector-676612778
```
and never finishes (nothing is extracted in `/var/tmp/image-inspector-676612778`).

I think it's because we have to replace the obsolete `CopyFromContainer` with `DownloadFromContainer`.

Once we'll switch we'll have to make sure that the new API call works for Fedora, CentOS and RHEL.

cc @enoodle @pweil-

**Comment by simon3z** [comment]
This worked for me:

```diff
diff --git a/pkg/inspector/image-inspector.go b/pkg/inspector/image-inspector.go
index 8919b0a..892d22c 100644
--- a/pkg/inspector/image-inspector.go
+++ b/pkg/inspector/image-inspector.go
@@ -323,18 +323,20 @@ func (i *defaultImageInspector) createAndExtractImage(client *docker.Client, con
        // the reader to read.
        errorChannel := make(chan error)
        go func() {
-               errorChannel <- client.CopyFromContainer(docker.CopyFromContainerOptions{
-                       Container:    container.ID,
-                       OutputStream: writer,
-                       Resource:     "/",
-               })
+               errorChannel <- client.DownloadFromContainer(
+                       container.ID,
+                       docker.DownloadFromContainerOptions{
+                               OutputStream: writer,
+                               Path:     "/",
+                       },
+               )
        }()
```

@enoodle please don't take my word for it... you have to research and make sure this is compatible on all docker versions, etc.

**Comment by simon3z** [comment]
If fixing this is not critical for the ManageIQ 4.2 delivery we can postpone it to the next build but we have to be sure that the current code (and current images) work perfectly on the platforms we are supporting (RHEL7-like even with the newest docker images).

**Comment by pweil-** [comment]
It looks like the `archive` endpoint was introduced in the [v1.20 api changes](https://docs.docker.com/engine/reference/api/docker_remote_api/#v120-api-changes).  This means it should be supported back to [version 1.8 of docker](https://docs.docker.com/engine/reference/api/docker_remote_api/) so I think it is a safe chagne.

**Comment by enoodle** [comment]
`DownloadFromContainer` is using the `archive` endpoint [1] so it seems good for us. I tried this on docker 1.12 and it fixed this problem for me too. I am now checking to see that it also works well on our ManageIQ use cases (with docker 1.10 ).

[1] https://github.com/fsouza/go-dockerclient/blob/b21e1152923f46354476a3befa5b7aab0f441b4c/container.go#L1201
