### ISSUE TITLE
Running image-inspector through ManageIQ - could not find RHEL dist

### ISSUE THREAD

**Issue by LarsMilland** [openshift/image-inspector#36]
Hi

I am trying to run the image-inspector - version 2.1 on an OpenShift Origin installation where the image-inspector is launched through ManageIQ as pods on the namespace where I also have ManageIQ running.

So I would be running this image of dockerhub: openshift/image-inspector:2.1

The image-inspector starts up fine, can download and extract the image I request to be scanned with "Smartstate Analysis" in ManageIQ, but the image-inspector is complaining that it cannot determine the RHEL distribution that I am running on - as this log extract is showing.

...
OpenSCAP scanning /var/tmp/image-inspector-079165993. Placing results in /var/tmp/image-inspector-scan-results-896793972
2017/03/14 09:02:47 Unable to scan image: Unable to run OpenSCAP: Unable to get RHEL distribution number: could not find RHEL dist
...

Any good suggestions? Would the serviceaccount on OpenShift that is used to launch the image-inspector docker container need some more privileges, or is there maybe something else wrong?

I am running the OpenShift Origin instance on RHEL 7.3.

Best regards
Lars Milland

**Comment by simon3z** [comment]
@LarsMilland is the image a RHEL image that OpenSCAP can scan? Remember that OpenSCAP supports only RHEL6/7.

cc @enoodle

**Comment by LarsMilland** [comment]
Understood - and it was of course not a RHEL based image I was trying to scan.
