### ISSUE TITLE
Sample example doesn't work: could not find RHEL dist

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/image-inspector#51]
```
$ docker run -ti --rm --privileged -v $PWD/asdqwexxx:/src -p 8080:8080 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  openshift/image-inspector --image=fedora:20 --scan-results-dir /src \
  --scan-type=openscap --path=/tmp/image-content
2017/05/31 15:00:05 Pulling image fedora:20
2017/05/31 15:00:08 Extracting image fedora:20 to /tmp/image-content
2017/05/31 15:00:11 OpenSCAP scanning /tmp/image-content. Placing results in /src
2017/05/31 15:00:12 Unable to scan image: Unable to run OpenSCAP: Unable to get RHEL distribution number: could not find RHEL dist
```

**Comment by simon3z** [comment]
@TomasTomecek currently we are supporting only RHEL distributions because there is an official CVE feed maintained. Are you aware of a Fedora CVE feed that we could use? If so we can look into supporting it (for example we know that there is no CVE feed for CentOS, see #40)

**Comment by TomasTomecek** [comment]
I got the example from readme, so it would nice to provide sensible examples.

**Comment by simon3z** [comment]
@TomasTomecek if `--image=rhel7/rhel:latest` is working for you could you send a PR to fix the README? Thanks!

**Comment by TomasTomecek** [comment]
It didn't work with rhel6, but it does with rhel7; PR opened.
