### ISSUE TITLE
Provide release binaries on Github

### ISSUE THREAD

**Issue by mfojtik** [openshift/image-inspector#56]
We should provide release binaries people can just download and use. Using this via docker image is cool, but if somebody wants to try this out and he has to deal with godeps, he will probably freak out ;-)

@simon3z @pweil- FYI

**Comment by simon3z** [comment]
@mfojtik we're maintaining builds here:

https://hub.docker.com/r/openshift/image-inspector/

> Using this via docker image is cool, but if somebody wants to try this out and he has to deal with godeps, he will probably freak out ;-)

@mfojtik what godeps are you referring to for the docker image?

**Comment by mfojtik** [comment]
@simon3z that is cool for users that want to run this via docker run. For users that want to run it locally, without docker, they have to build the binary themself and for "normal" users that is not easy.

**Comment by simon3z** [comment]
> @simon3z that is cool for users that want to run this via docker run. For users that want to run it locally, without docker, they have to build the binary themself and for "normal" users that is not easy.

@mfojtik any automation that we leverage from the OpenShift infrastructure? (I assume you're doing this already for Origin).

**Comment by mfojtik** [comment]
@simon3z i think we still do the releases manually ;-)

**Comment by simon3z** [comment]
> @simon3z i think we still do the releases manually ;-)

@mfojtik built from our laptops? :blush:

**Comment by mfojtik** [comment]
@smarterclayton ^ :)
