### ISSUE TITLE
Warn but don't fail when loading configs

### ISSUE THREAD

**Issue by pweil-** [openshift/image-inspector#6]
Suggestion: since we'll now also always have a default empty auth we could warn but not fail if errors are encountered when loading auth files.  If the image still fails to pull we'll eventually have a hard error.

https://github.com/openshift/image-inspector/blob/master/pkg/inspector/image-inspector.go#L358

@simon3z @enoodle WDYT?

**Comment by simon3z** [comment]
Good idea :+1:
