### ISSUE TITLE
Parameter "cve-url" should enforce using https portocol

### ISSUE THREAD

**Issue by enoodle** [openshift/image-inspector#70]
It was mentioned to me that a user can use the parameter to give an unsecured "http://" URL.
I suggest that this parameter will be changed to expect a URL without a protocol and use it as https.

**Comment by enoodle** [comment]
@ilackarms @simon3z @pweil- WDYT?

**Comment by ilackarms** [comment]
for the sake of argument, a user may be serving their own locally curated CVE data over HTTP (maybe it's behind their company firewall?). Is there a reason we want to disable that use case (or force the user to use HTTPS)?

I'm not against the change, just trying to understand the motivation

**Comment by enoodle** [comment]
@ilackarms This might be "paternal" but also help round up the security constraints in this security aware application.

**Comment by ilackarms** [comment]
@enoodle seems like a reasonable change

**Comment by pweil-** [comment]
Forcing https is breaking backwards compatibility for the command.  If we say it's a bug and never should've been that way then that's one thing but folks need to be aware that they can break on upgrade if we move with this change.

**Comment by enoodle** [comment]
@pweil- Is someone currently using this? This can can be scheduled for the next version bump.

**Comment by pweil-** [comment]
No clue :smile: but not that I know of.  But that's the joy of open source
