### ISSUE TITLE
how to integrate image-inspector with jenkins slave?

### ISSUE THREAD

**Issue by sukritpol** [openshift/image-inspector#83]
I try to create jenkins slave to run image-inspector to scan image but i cant do that.

Could you share me how to integrate with jenkins slave for pipeline?
if cant do that, i'll change my solution to scan docker image.

problem
- cant run docker image in jenkins slave.
- but if run image-inspector as openshift container , we can scan image

Thanks

**Comment by ilackarms** [comment]
you'll need docker at least installed on your jenkins slave. docker is used to pull and extract the target image. the arguments for running the image-inspector binary are available via the readme:

```
sudo image-inspector --image=fedora:22 --path=/tmp/image-content --scan-type=openscap
		--serve 0.0.0.0:8080 --chroot
```

You can run this in the background and poll the image inspector for the results of the scan. An example of how to write an image inspector client is available here: https://github.com/moolitayer/image-inspector-client

**Comment by sukritpol** [comment]
@ilackarms thank you , i'll try your solution. :)
