### ISSUE TITLE
Start building image-inspector container image at CentOS community container pipeline

### ISSUE THREAD

**Issue by navidshaikh** [openshift/image-inspector#88]
This issue is to track indexing image-inspector repository to build at [CentOS community container pipeline service](https://github.com/CentOS/container-pipeline-service).

A successful build indexes image at https://registry.centos.org/

Docker pull URL like registry.centos.org/namespace/image-inspector

Since `centos:7` is used as a base image, the Dockerfile should not need many changes to onboard project on build service.

With project configured to build at pipeline service, there will be automatic rebuilds of image, when
  - there is a change pushed to the repository
  - the underlying base image got an update

To index this project to build at pipeline service, all it needs is to add a YAML file `cccp.yml` in the project repository with 
```
job-id: image-inspector
```

**Comment by simon3z** [comment]
cc @enoodle

**Comment by navidshaikh** [comment]
`openshift/image-inspector` container image is not available at `registry.centos.org`

`docker pull registry.centos.org/openshift/image-inspector:latest`
